### ISSUE TITLE
I can't update my games

### ISSUE THREAD

**Issue by komissarov-qa-auto** [vKolerts/sidenoder#36]
I click installed button and I see a list of my installed games, then i click "check mount for updates", then he thinks for a couple of seconds and gives an empty list
If i click remote, i see empty list :(

log:
[3/18/2023, 1:05:42 PM.853] get_installed 50 
[3/18/2023, 1:05:46 PM.740] get_installed_with_updates received 
[3/18/2023, 1:05:51 PM.967] ERROR: Can`t open folder /var/folders/zm/rdq94z8n0yd6gwfbwbd0k5vc0000gn/T/mnt/Quest Games [Error: EIO: i/o error, scandir '/var/folders/zm/rdq94z8n0yd6gwfbwbd0k5vc0000gn/T/mnt/Quest Games'] {
  errno: -5,
  code: 'EIO',
  syscall: 'scandir',
  path: '/var/folders/zm/rdq94z8n0yd6gwfbwbd0k5vc0000gn/T/mnt/Quest Games'
} 

Error:
https://radikal.host/i/XJgVc1
settings:
https://radikal.host/i/XJ2x2u
https://radikal.host/i/XJ273r
https://ibb.co/n1vKHf9

**Comment by KaladinDMP** [comment]
This is because your using a old nonworking config. This is expected behaviour. Get a working config and this may work as expected. FFA is now paid only. They are called NIF and VRP only gives working sidenoder configs for money now as well only it's much cheaper. $40± for NIF compared to $1 a month for VRP

**Comment by komissarov-qa-auto** [comment]
it's easier to install parallels desktop + rockie sideloader and buy a lot of shawarma for these $ 40
